<?php

add_action( 'init', function () {
	$post = array(
		'label'                 => __( 'Projet', 'text_domain' ),
		'description'           => __( 'Un projet', 'text_domain' ),
		'labels'                => array(
      'name'                  => _x( 'Projet', 'Post Type General Name', 'text_domain' ),
      'singular_name'         => _x( 'Projet', 'Post Type Singular Name', 'text_domain' ),
      'menu_name'             => __( 'Projets', 'text_domain' ),
      'name_admin_bar'        => __( 'Projets', 'text_domain' ),
      'archives'              => __( 'Item Archives', 'text_domain' ),
      'attributes'            => __( 'Item Attributes', 'text_domain' ),
      'all_items'             => __( 'Tous les projets', 'text_domain' ),
      'add_new_item'          => __( 'Ajouter un projet', 'text_domain' ),
      'add_new'               => __( 'Ajouter un projet', 'text_domain' ),
      'new_item'              => __( 'Nouveau projet', 'text_domain' ),
      'edit_item'             => __( 'Modifier un projet', 'text_domain' ),
      'update_item'           => __( 'Mettre à jour un projet', 'text_domain' ),
      'view_item'             => __( 'Voir le projet', 'text_domain' ),
      'view_items'            => __( 'Voir les projets', 'text_domain' ),
      'search_items'          => __( 'Chercher les projets', 'text_domain' ),
      'not_found'             => __( 'Non trouvé', 'text_domain' ),
      'not_found_in_trash'    => __( 'Non trouvé dans la poubelle', 'text_domain' ),
      'featured_image'        => __( 'Featured Image', 'text_domain' ),
      'set_featured_image'    => __( 'Set featured image', 'text_domain' ),
      'remove_featured_image' => __( 'Remove featured image', 'text_domain' ),
      'use_featured_image'    => __( 'Use as featured image', 'text_domain' ),
      'insert_into_item'      => __( 'Insert into item', 'text_domain' ),
      'uploaded_to_this_item' => __( 'Uploaded to this item', 'text_domain' ),
      'items_list'            => __( 'Items list', 'text_domain' ),
      'items_list_navigation' => __( 'Items list navigation', 'text_domain' ),
      'filter_items_list'     => __( 'Filter items list', 'text_domain' ),
    ),
		'supports'              => array( 'title' ),
    'taxonomies'            => array( 'category' ),
    'featured_image'        => __( 'Featured Image', 'text_domain' ),
		'set_featured_image'    => __( 'Set featured image', 'text_domain' ),
		'remove_featured_image' => __( 'Remove featured image', 'text_domain' ),
		'use_featured_image'    => __( 'Use as featured image', 'text_domain' ),
		'hierarchical'          => false,
		'public'                => true,
		'show_ui'               => true,
		'show_in_menu'          => true,
		'menu_position'         => 5,
		'menu_icon'             => 'dashicons-media-video',
		'show_in_admin_bar'     => true,
		'show_in_nav_menus'     => true,
		'can_export'            => true,
		'has_archive'           => true,
		'exclude_from_search'   => false,
		'publicly_queryable'    => true,
		'capability_type'       => 'page',
    'show_in_rest'          => true,
	);
  register_post_type( POST_TYPE__PROJECT , $post );
});